// flow-typed signature: 2dc079e14438f7c1f9b178d52564cd22
// flow-typed version: <<STUB>>/styled-normalize_v^3.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-normalize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-normalize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-normalize/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-normalize/dist/index.js' {
  declare module.exports: $Exports<'styled-normalize/dist/index'>;
}
